---

- name: "Create base directory for IDEX staking replicator data"
  file:
    path: '{{ idex_staking_node__data_dir }}'
    owner: root
    group: root
    mode: '750'
    state: directory

- name: 'Create IDEX staking replicator subdirectories'
  file:
    path: "{{ idex_staking_node__data_dir }}/{{ item }}"
    owner: root
    group: root
    mode: '750'
    state: directory
  loop:
    - conf
    - logs

- name: Setup IDEX staking replicator docker container
  docker_container:
    user: root
    image: idexio/staking-replicator:{{ idex_staking_node__version }}
    name: "{{ idex_staking_node__container_name }}"
    state: started
    restart_policy: unless-stopped
    mounts:
      - source: '{{ idex_staking_node__data_dir }}/conf'
        target: /conf
        type: bind
        read_only: no
      - source: '{{ idex_staking_node__data_dir }}/logs'
        target: /logs
        type: bind
        read_only: no
    env:
      API_KEY: '{{ idex_staking_node__api_key }}'
      IDEX_STAKING_ACCESS_LOG_PATH: /logs/access.log
      IDEX_STAKING_ACTIVITY_LOG_PATH: /logs/activity.log
      IDEX_STAKING_ERROR_LOG_PATH: /logs/errors.log
    published_ports:
      - '0.0.0.0:8081:8081'
